### PR TITLE
fixed to run on Recon 11

### PR DESCRIPTION
**Pull request by Murf**
Resized Toggle_Fader_4frames.png to be vertically divisible by 4 AND be able to be reduced by 20% and stay an integer height per Reason Studio's development requirements (ie., increased height from 852 to 860 pixels)

### CODE REVIEW

**Comment by ypujante** [comment]
Thank you for contributing the patch for Recon 11. This device was created with SDK 2.2 and the change to `hdgui_2D.lua` won't work (per documentation: "_File format version of the hdgui.lua file. Must be "1.0" or "2.0" for hdgui.lua. Must be "1.0" for hdgui_2D.lua. Required_."

I am also not sure why you changed the version number the way you did. It should be maybe `1.0.1f1` but certainly not `1.0.0` (which has already been released).

**Comment by Murf** [comment]
Hi!
Thanks for replying, I changed the hdgui_2D.lua version to 2.0 so it could
build with the latest SDK.
The RE version i set to 1.0.0 so that any combinator patches my beta
testers give me that have CVA-7 in it will work in my recon, it was
purely a local dev thing.
I probably should have only included the altered .png file and nothing else.

Murf.

**Comment by ypujante** [comment]
At some point in the future, I will most likely upgrade all my devices to use the latest SDK at which point I will definitely have to fix the kind of issue affecting the image. In the meantime I am holding off on any change (besides bug fixes of course).

**Comment by Murf** [comment]
Cool no problem, I just thought you might like to know how to fix the error
in Recon :)
I think PH will be asking us to do 4K assets soon, and you may have to
rebuild then anyway, probably with a whole new set of assets.
Murf

**Comment by ypujante** [comment]
The plugin has been updated to use the newly open sourced `re-cmake` CMake based build framework and as a result was also updated to run in the latest Recon. The changes you have in this pull request have essentially been applied part of this effort. Thanks for the PR.

**Comment by Murf** [comment]
Awesome thanks Yan!

**Pull request closed without merging**
